### ISSUE TITLE
Cannot make with mingw (win10)

### ISSUE THREAD

**Issue by dianx93** [cnlohr/noeuclid#38]
When trying to make I get this error:
```
process_begin: CreateProcess(NULL, uname, ...) failed.
mingw32-make: Makefile:7: pipe: No error
g++  -std=c++11 -DGLEW_STATIC -DGL_GLEXT_PROTOTYPES -g -Wall -O2   -c -o noeuclid.o noeuclid.cpp
noeuclid.cpp:29:21: fatal error: GL/glew.h: No such file or directory
 #include <GL/glew.h>
                     ^
compilation terminated.
<builtin>: recipe for target 'noeuclid.o' failed
mingw32-make: *** [noeuclid.o] Error 1
```

**Comment by kkragoth** [comment]
Hello, it seems like **it's not related with project** but you are not including necessary GL stuff.

In linux you can follow readme.md and install needed packages with '$sudo apt-get install build-essential libtcc-dev libsfml-dev libglew-dev'

Since you're using Win10 I guess you'll have to download necessary packages (i mean: libraries/headers) manually and add them to compiler path. 

Try reading compiler errors and downloading and installing required packages i.e : fatal error: 'GL/glew.h: No such file or director' =>http://glew.sourceforge.net/

**Comment by dianx93** [comment]
I downloaded glew but I don't know how to add it to compiler path, i guess I have to modify Makefile? but how?

**Comment by dianx93** [comment]
Also in the 'Windows' folder there appears to be a GL folder with glew already in there. Doesn't seem to matter to the compiler though.

**Comment by phiresky** [comment]
Note that this never fully worked on Windows. I got it [to partially work at some point](https://github.com/cnlohr/noeuclid/issues/9#issuecomment-59992458), but even then the mouse had weird behaviour. So getting it to run would probably be more work than getting it to compile.
